lib/builder.js
This fixes bug #97 for me. Let me know what you think.
=> Check if a local theme is present.

index.js, lib/exportResume.js
=> Added support for path.resolve when determining export target

lib/test.js
Replaced "JSONLInt" with "JSONLint."
=> Fix typo in lib/test.js

lib/serve.js
adding the missing `dir` param
=> fix serve task

lib/builder/index.js, lib/serve.js
Fixed error handling when resume is not found and when template cannot be found.
Fixed use of readline API to avoid undefined clearLine().
=> Fixed error handling

README.md
To help with https://github.com/jsonresume/resume-cli/issues/189
=> Add login command

lib/pre-flow/get-resume.js
With this code you can use --resume= process argument to point the resume.json location.
=> Support to specify resume.json path via command line argument

lib/init-resume.json, lib/init.js
=> Fixes Resume Init #323

lib/test.js
=> fix(test):issue 326

package-lock.json, package.json
To support the following:
- [v0.1.3] - add education.url
- [v0.1.2] - add $schema property
- [v0.1.1] - better dates
=> fix: bumped schema version

index.js, lib/builder/index.js, lib/export-resume/index.js
Normalize theme package name before passing to program actions, and delegate module resolution to Node.
=> fix(theme): fix theme package lookup

.github/workflows/main.yml, .lintstagedrc.json, .prettierrc.json, README.md, index.js, lib/builder/index.js, lib/export-resume/index.js, lib/index.js, lib/init-resume.json, lib/init.js, lib/pre-flow/check-pkg-version.js, lib/pre-flow/get-config.js, lib/pre-flow/get-resume.js, lib/pre-flow/index.js, lib/pre-flow/validate-schema.js, lib/pre.js, lib/serve.js, lib/test.js, lib/version.js, package-lock.json, package.json, test/resume.json, test/validate.test.js
Format staged files on pre-commit using Prettier, and check for unformatted files in the CI.
The codebase has a mix of single and double-quoted strings, so I picked the former. Also, print multi-line trailing commas wherever possible, since we don't support Node.js < 8.
Relates to #359.
=> style(prettier): setup Prettier and format all files

lib/export-resume/index.js
feat(theme): added ability to specify viewport for pdf generation in the theme definition
=> feat(theme): added ability to specify viewport for pdf generation in the theme definition

lib/serve.js, package-lock.json, package.json
When you are using `resume serve` command, once resume.json file changed, will auto rebuild html file and auto reload browser, no need to refresh browser manually.
=> refactor: add browser auto-reload feature to serve function

lib/main.js
This fixes a regression introduced in #440 where export and serve got broken.
=> fix: addressing regressions to serve and export

README.md, jest.config.js, lib/get-resume.js, lib/get-resume.test.js, lib/main.js, package-lock.json, package.json
See the additions to readme.md for a description of the feature
=> feat: get-resume supports yaml, input stream, and quaff-style directories

lib/get-schema.js, lib/main.js, lib/main.test.js, lib/test-utils/mocked-volume-builder.js, lib/validate.js, lib/validate.test.js
resolves https://github.com/jsonresume/resume-cli/issues/435
=> refactor: use-commander-to-parse-schema-cli-arg

README.md
The correct command for validating the JSONResume file would be `validate`, rather than `test`.
=> docs(README.md): update CLI command for validation

lib/export-resume.js
=> fix: Correctly call renderHtml in createPdf

lib/builder.js, lib/render-html.js, lib/render-html.test.js
=> fix(theme): fix serving and exporting local themes
