index.js
Changes the text when running `resume --help` from `Usage: resume [options] [command]` to `Usage: resume [command] [options]`.
The reason for the PR is that the help text should be more clear on the order you should pass  arguments to the program.
=> Display options after command in the help text

lib/builder.js
Ideally the whole thing would use promises and I wouldn't have to resort to ugly hacks like `.then(cb.bind(null, null), cb)` but this should suffice for now.
=> Adds promise support

lib/builder/index.js
`resume serve` failed for me with a error about the module 'package' wasn't found in the current directory. 
This patch makes sure to initialize the `packageJson` variable with a empty object so that if the package isn't found we just continue as we would normally instead of failing hard.
:rocket:
=> Set a default for package json

index.js
Markdown doesn't seem to be supported by `export`.  Perhaps it should be removed from the cli description of the command?
=> remove mention of .md

index.js, lib/serve.js
Currently, resume-cli utilizes node-static in an ad-hoc way. Because the static server's path is root directory, all other unnecessary sources are exposed to the public. To avoid such exposure, I added public directory as follows:
1. The default public directory is 'public'.
2. A user can choose a public directory with an option ('-d', '--dir').
3. The output path of 'index.html' is moved to the public directory.
=> adding default public directory and option for choosing it. (default: 'public')

index.js, lib/builder/index.js, lib/serve.js
This PR adds a `-r` and `--resume` parameter for the serve command, to allow specifying a different `resume.json` file. This makes it easier to test a theme with your own resume in a different directory. For example I have:
~/src/jsonresume-theme-onepage
and:
~/src/resume/resume.json
And now I can do this:
~/s/jsonresume-theme-onepage ❯❯❯ resume serve -r ~/src/resume/resume.json
=> Allow serve to use a resume.json file in a different directory

lib/register/validate.js
I was trying to register "et" as a username and didn't understand why it wouldn't accept my name. This improves the message to be more clear of the requirements.
=> Improve validation message

index.js
The terminal prompt used to show "/Users/astephen/Documents/Personal/resume-cli/test". 
Changed it so it would say "/Users/astephen/Documents/Personal/resume-cli/test.pdf" instead
=> fixed terminal message so that the proper export path shows up

lib/export-resume/index.js, package.json
I saw this pull request #256 about changing to Chrome exporting PDFs and @chasebolt recommended using puppeteer so it is independent of an installed Chrome. This is my shot at it (also, this my first pull request and contribution to OSS, so sorry if I screw up).
This doesn't fix all issues with exporting to PDF, some of them are issues with a theme. The default Flat theme is a three page pdf but a single page/print friendly theme(Spartacus-Prime) does look great.
This does keep the same functionality and even speeds up exporting over html-to-pdf. We could extend export args to allow selection of paper size(default is Letter, it was the old default) and add the ability to create an image of the resume using puppeteer.
=> Fix exports for PDSs via puppeteer

lib/test.js
resume-schema uses error-first callbacks, as illustrated in their own readme. https://github.com/jsonresume/resume-schema#readme
Additionally, to avoid problems like this in the future, you should absolutely pin your dependency versions in package.json, rather than always pulling latest. Otherwise, dependencies can change their signature and break your library without warning.
=> fix resume json validation

lib/export-resume/index.js, package-lock.json, package.json
Exported data is not encoded properly to be read by puppeteer.  Use new
dependency [btoa](https://www.npmjs.com/package/btoa) to polyfill
browser btoa to base64 encode the html content into url-safe format.
Commit also updates module version in package-lock.json.
=> fix(export): fix encoding in createPdf func

lib/test.js
#331
Errors are now passed in, but errors passed in are not an object, they are an array with ZSchema objects. This PR changes the test.js code in 2 places to accomodate the new error format. 
Tested by running against a valid resume.json, then adding bad characters to resume.json and running again to ensure that badly formatted JSON still produces the suggestion to use JSON linter.
=> Patch for error format issue

.travis.yml, index.js, lib/pre-flow/validate-schema.js, lib/pre.js, lib/test.js, package-lock.json, package.json, test/index.js, test/validate.test.js
This is re: "move the validator to a separate resume-validator repo" from https://github.com/jsonresume/resume-schema/issues/349 (and specifically https://github.com/jsonresume/resume-schema/issues/349#issuecomment-608274390).
To my knowledge, this project (resume-cli) is the only project that depends on resume-schema, so we should be able to remove the validate export and related code from resume-schema once / if the branch for this PR is merged.
=> removed dependency on validate from *-schema. using zschema directly instead

index.js
Commander does not call custom option processor when the respective value is not specified by the user, so we must use the normalized theme name by default.
=> fix(theme): use normalized theme name by default

README.md
In order to have doc be consistent with available features, the readme should be updated to have "markdown" removed as an export option filetype.
This is a small edit, but it makes it more clear that directly exporting to markdown isn't supported 
- for interest, see also: https://github.com/jsonresume/resume-cli/pull/300
- see also, only supporting HTML and pdf: https://github.com/jsonresume/resume-cli/blob/06e0b81d3e19d08b7d631667e0dc4f5026ad602f/lib/export-resume/index.js#L12-L34
- EDIT I just noticed there's an issue for this here https://github.com/jsonresume/resume-cli/issues/387 This was coincidental timing and me not checking the issue for it, my bad if someone else wanted to do a quick PR for this
=> docs: remove readme content about exporting markdown

.github/dependabot.yml
In order to have automated dependency updates take place for npm and github actions itself, incorporate a basic dependabot config file (https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#configuration-options-for-dependabotyml)
note: I realize this PR was unsolicited and doesn't have an associated request issue, but it's an easy PR to put together real quick. It looks like there are other automated dependency PRs such as depshield (https://github.com/jsonresume/resume-cli/issues/381) or greenkeeper (now snyk) (https://github.com/jsonresume/resume-schema/pull/379), however github actions is fairly straightforward and is integrated directly.
feel free to edit, close, etc., thanks for the time 👍
=> ci: incorporate dependabot config

.github/dependabot.yml, lib/export-resume/index.js
PRs (e.g. https://github.com/jsonresume/resume-cli/pull/398) are currently failing on prettier being upset about formatting, specifically (https://github.com/jsonresume/resume-cli/pull/398/checks?check_run_id=1267012487):
>
> Run npm run format:check
> 
> > resume-cli@0.0.0-development format:check /home/runner/work/resume-cli/resume-cli
> > prettier --check .
> 
> Checking formatting...
> [warn] .github/dependabot.yml
> [warn] lib/export-resume/index.js
> [warn] Code style issues found in the above file(s). Forgot to run Prettier?
> npm ERR! code ELIFECYCLE
>
but this should square those issues away; just ran `npm run format` to let `prettier` format in-place.
=> style(prettier): run inplace formatting writes

.github/dependabot.yml
see also: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#commit-message
In order to allow the PR linter to pass commit naming validation ([see here for an example of the lint checking failing](https://github.com/jsonresume/resume-cli/pull/402/checks?check_run_id=1310948384)), update the dependabot configuration file to prefix commits with `chore(deps): xyzabc`, which is based on [this PR](https://github.com/jsonresume/resume-cli/commit/62cf81174d9a11cf5382e9f75023fa1216c98fc8) appearing to use the same style
... It's so close to cooperating, gdangit.
=> ci: have dependabot PRs be prefixed with prefix commit messages

lib/builder/index.js
When using the command `resume server --theme [insert them name]`, the request got back a 400 error with the error message posted down below. 
The PR creates a denormalizeTheme function in the builder 'index.js' file (mostly for readability) and uses that function to denormalize the theme name from 'jsonresume-theme-even' to 'even'.
=> fix: use denormalize theme name for server request

index.js, lib/index.js
This code changes the mass import of `lib/*` as an index object and instead requires the modules inside of `lib` by their actual path. Doing so allows for stronger code analysis since the modules in lib are now referenced as variables instead of properties on an object.
I've removed `lib/index.js` to discourage the pattern of referencing exported modules as properties of an object going forward.
=> refactor: removing index from lib so we can better trace module dependencies

.eslintrc.json, README.md, babel.config.js, lib/main.js, package-lock.json, package.json
in reference to [issue #432 "support modern javascript"](../issues/432), this PR aims to add support for modern javascript to this project by transpiling code with babel before it is run.
=> build(babel): transpiling with babel so we can use modern javascript

lib/render-html.js
we were getting ci failures when running tests in node greater than version 10. This fixes that problem for the current set of tests.
=> fix: fixing theme resolution for node greater than version 10

lib/export-resume.js
As discussed in #408 this fix will calculate the theme package from the local context instead the global one. 
This will align the calculation of the theme package path, although in the future it will be interesting to unify every theme package access. 
With these changes it will be possible to use:
``` bash
npm install jsonresume-theme-my-theme
resume export resume.pdf --format pdf --theme my-theme
resume export resume.html --format html --theme my-theme
```
=> fix: export pdf get package theme from local context

package-lock.json, package.json
This fixes chromium installation issues on Apple Silicon machines. Jest tests appear to pass, and I was able to render my personal `resume.json` to pdf on an M1 MacBook Pro after upgrading.
Note: I had to completely remove `node_modules` and run `npm i` again after bumping to get puppeteer to install chromium.
Users may have [previously hacked their puppeteer installations via `~/.zshrc`](https://linguinecode.com/post/how-to-fix-m1-mac-puppeteer-chromium-arm64-bug) like so:
```zsh
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
export PUPPETEER_EXECUTABLE_PATH=`which chromium`
```
Those users may need to remove those two lines, start a new terminal emulator tab/instance, and re-install `resume-cli` to get the deps resolved.
=> fix(deps): bump puppeteer to `^16.1.0`, fix Apple Silicon installation

.github/workflows/pr.yml, .github/workflows/release.yml, .github/workflows/test.yml, CONTRIBUTING.md, README.md
Mostly revamps the README.
* Update the badges so they actually work.
* Clarify that the project is lacking maintenance and so it's recommended to use a third-party client.
* Clarify that `resume serve` is not for production use
* Rewords parts of the README, particularly capitalization.
A few changes are also made in CI. In my last PR I split up testing and releasing so that we could test PRs. Another maintainer noted that we should run tests before a release to be safe, so this adds the tests back in the release action.
* Closes https://github.com/jsonresume/resume-cli/pull/472
* Closes https://github.com/jsonresume/resume-cli/issues/563
* See https://github.com/jsonresume/resume-cli/issues/767#issuecomment-1821229157
=> chore: revise health files

.github/workflows/release.yml
We're currently unable to make releases as our pipeline uses the latest version of `conventional-changelog-conventionalcommits`, but the latest release has changed.
For an immediate fix, let's pin it to the last version we know it works with.
(Based on the last release taking place in October 2022.)
Later, I can upgrade both `cycjimmy/semantic-release-action` and `conventional-changelog-conventionalcommits` to the latest versions that support each other.
=> ci: pin version of conventional-changelog-conventionalcommits

.github/workflows/release.yml
Fixes releases by updating and pinning the versions of `cycjimmy/semantic-release-action` and `conventional-changelog-conventionalcommits`.
=> ci: update actions versions

package-lock.json, package.json
Upgrades to the latest version of puppeteer we can use without making other changes to the project, namely increasing the minimum supported Node.js version.
* Works towards https://github.com/jsonresume/resume-cli/issues/760
=> chore: upgrade puppeteer to v18
